"""Commit reference index and revert detection for issue tracking."""

from __future__ import annotations

import re
from typing import Protocol

from gitrelevance.git.commits import Commit
from gitrelevance.git.repository import GitRepository


# Cache key for the commit reference index on GitRepository instances
_INDEX_CACHE_KEY = "_gitrelevance_commit_reference_index"


def build_commit_reference_index(repo: GitRepository) -> dict[int, list[Commit]]:
    """Build an index mapping issue numbers to commits that reference them.

    This function walks the commit log exactly once and caches the result
    on the repository instance for reuse. This is critical for performance
    with large repositories (10,000+ commits).

    Issue references are detected by patterns like #123 or GH-123 in commit
    messages, where N is an issue number.

    Args:
        repo: The GitRepository to build the index for

    Returns:
        Dictionary mapping issue numbers to lists of commits referencing them
    """
    # Check if index already cached on repo instance
    if hasattr(repo, _INDEX_CACHE_KEY):
        return getattr(repo, _INDEX_CACHE_KEY)

    # Build the index by walking commits once
    index: dict[int, list[Commit]] = {}

    # Pattern to match issue references: #123 or GH-123
    issue_pattern = re.compile(r"(?:^|\s)#(\d+)|(?:^|\s)GH-(\d+)")

    for commit in repo.commits_since(None):
        message = commit.message

        # Find all issue references in the commit message
        matches = issue_pattern.findall(message)

        for match in matches:
            # Each match is a tuple of (group1, group2), one will be empty
            issue_num_str = match[0] or match[1]
            if issue_num_str:
                try:
                    issue_num = int(issue_num_str)
                    if issue_num not in index:
                        index[issue_num] = []
                    index[issue_num].append(commit)
                except ValueError:
                    continue

    # Cache the index on the repo instance
    setattr(repo, _INDEX_CACHE_KEY, index)

    return index


def commits_referencing(repo: GitRepository, issue_number: int) -> list[Commit]:
    """Get all commits that reference a specific issue.

    Uses the cached index instead of scanning history itself.

    Args:
        repo: The GitRepository to search
        issue_number: The issue number to find commits for

    Returns:
        List of commits referencing the issue, newest first
    """
    index = build_commit_reference_index(repo)
    return index.get(issue_number, [])


class RevertDetector(Protocol):
    """Protocol for detecting reverts of commits.

    Future implementations could use inverse-diff comparison,
    message heuristics, patch similarity, or semantic analysis.
    """

    def find_reverts_of(self, repo: GitRepository, commit_sha: str) -> list[Commit]:
        """Find commits that revert the specified commit.

        Args:
            repo: The GitRepository to search
            commit_sha: SHA of the commit to find reverts of

        Returns:
            List of commits that revert the specified commit
        """
        ...


class GitNativeRevertDetector:
    """MVP implementation: detects only commits Git's own revert machinery produced.

    This detector uses Git's native revert detection, which relies on
    the parent/trailer relationship that 'git revert' creates. It does
    NOT use free-text commit-message pattern matching or inverse-diff
    comparison.
    """

    def find_reverts_of(self, repo: GitRepository, commit_sha: str) -> list[Commit]:
        """Find commits that revert the specified commit using Git's native detection.

        ``git revert`` always inserts exactly this sentence into the commit
        message::

            This reverts commit <full-sha>.

        That line is generated by Git's own revert machinery and is the
        authoritative signal we use.  We deliberately do NOT match commits
        that merely mention "revert" in their message (the fake-revert test
        exercises this).

        Args:
            repo: The GitRepository to search
            commit_sha: SHA of the commit to find reverts of

        Returns:
            List of commits that revert the specified commit, or empty list
        """
        # Resolve the full SHA so partial SHAs compare correctly
        target_commit = repo.get_commit(commit_sha)
        if target_commit is None:
            return []
        full_sha = target_commit.sha

        reverts: list[Commit] = []
        for commit in repo.commits_since(None):
            # Look for the exact Git-generated trailer line.
            # git revert writes: "This reverts commit <sha>."
            # where <sha> is the full 40-character hex SHA.
            if f"This reverts commit {full_sha}." in commit.message:
                reverts.append(commit)

        return reverts


# Default detector instance (module-level singleton)
_default_detector: GitNativeRevertDetector | None = None


def default_revert_detector() -> RevertDetector:
    """Get the default revert detector.

    Returns the singleton instance of GitNativeRevertDetector.
    This can be swapped out later by reassigning the module-level variable
    or by providing an alternative factory.

    Returns:
        The default RevertDetector implementation
    """
    global _default_detector
    if _default_detector is None:
        _default_detector = GitNativeRevertDetector()
    return _default_detector
